#!/usr/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Eui Soo SON
#
# make_version_info.py -- generates a PyInstaller "version file" (a Windows
# VS_VERSION_INFO resource, written in PyInstaller's text format) so that
# dem2dged.exe and dem2dged_validate.exe carry File version / Product
# version / Company / Description metadata.
#
# WHY THIS EXISTS: neither dem2dged.spec nor dem2dged_validate.spec ever
# passed a `version=` argument to EXE(...), so the built .exe had NO Windows
# version resource at all -- right-click the exe > Properties > Details
# showed only the file name, with File description, File version, Product
# name, Product version and Copyright all blank.
#
# This script deliberately carries NO "# Version:" header of its own and is
# NOT one of the declarations audit_pure.py section 7 checks against
# dem2dged_lib.VERSION -- it has nothing to get out of sync, because it
# reads VERSION and RELEASE_STAGE out of dem2dged_lib.py as plain text every
# time it runs (see read_project_version() below) instead of hardcoding
# them. Whatever dem2dged_lib.VERSION says at build time is what ends up in
# the .exe -- the same "auto-detected, not hardcoded" approach dem2dged.spec
# already uses for the GDAL/PROJ data directories.
#
# Deliberately dependency-free (stdlib only -- no numpy, no osgeo) so it can
# run as the very first step of rebuild_exe.bat / rebuild_validate_exe.bat,
# before anything else about the build environment has been checked.
#
# Usage:
#   python make_version_info.py gui       [output_path]
#   python make_version_info.py validate  [output_path]
#
# output_path defaults to version_info_gui.txt / version_info_validate.txt
# next to this script. Both defaults are what dem2dged.spec /
# dem2dged_validate.spec look for via their `version=` argument.
#
# Called from, in this order of who runs it:
#   rebuild_exe.bat, rebuild_validate_exe.bat   (the normal build path)
#   build_exe.bat, build_validate_exe.bat       (the bootstrap/--version-file path)
#   RELEASE_CHECK_v0.45.py, BUILD_AND_PACKAGE.py (import the function directly)

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

COMPANY_NAME = "Eui Soo SON"
COPYRIGHT = ("Copyright (c) 2026 Eui Soo SON -- "
             "SPDX-License-Identifier: GPL-2.0-or-later")

# One entry per PyInstaller build target. internal_name / original_filename
# must match the `name=` EXE() uses in the matching .spec file.
PRODUCTS = {
    "gui": {
        "internal_name": "dem2dged",
        "original_filename": "dem2dged.exe",
        "file_description": "dem2dged - DEM to DGED Converter (GUI)",
        "product_name": "dem2dged",
        "default_output": "version_info_gui.txt",
    },
    "validate": {
        "internal_name": "dem2dged_validate",
        "original_filename": "dem2dged_validate.exe",
        "file_description": "dem2dged_validate - DGED Delivery Validator",
        "product_name": "dem2dged",
        "default_output": "version_info_validate.txt",
    },
}

# PyInstaller reads this file by exec'ing it in a namespace that predefines
# VSVersionInfo / FixedFileInfo / StringFileInfo / StringTable / StringStruct
# / VarFileInfo / VarStruct -- see:
# https://pyinstaller.org/en/stable/usage.html#capturing-windows-version-data
# '040904B0' / [1033, 1200] is the standard US-English, Unicode-codepage
# langID/codepage pair used in the overwhelming majority of version
# resources; there is nothing dem2dged-specific about that choice.
VERSION_FILE_TEMPLATE = u"""# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Eui Soo SON
# UTF-8
#
# Auto-generated by make_version_info.py -- DO NOT EDIT BY HAND.
# Regenerated on every build from dem2dged_lib.VERSION; hand edits are
# overwritten the next time rebuild_exe.bat / rebuild_validate_exe.bat runs.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({file_tuple}),
    prodvers=({file_tuple}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'{company_name}'),
           StringStruct(u'FileDescription', u'{file_description}'),
           StringStruct(u'FileVersion', u'{version_display}'),
           StringStruct(u'InternalName', u'{internal_name}'),
           StringStruct(u'LegalCopyright', u'{copyright}'),
           StringStruct(u'OriginalFilename', u'{original_filename}'),
           StringStruct(u'ProductName', u'{product_name}'),
           StringStruct(u'ProductVersion', u'{version_display}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


class VersionInfoError(Exception):
    """Raised when VERSION cannot be read/parsed from dem2dged_lib.py, or
    an unknown product key is requested. Callers that import this module
    (RELEASE_CHECK_v0.45.py, BUILD_AND_PACKAGE.py) catch this directly
    instead of the SystemExit a plain CLI script would raise, so a version-
    info failure never has a chance to look like an unrelated crash in
    whichever bigger script imported this one.
    """


def read_project_version(src_dir=HERE):
    """Read VERSION and RELEASE_STAGE out of dem2dged_lib.py as plain text.

    Deliberately does NOT `import dem2dged_lib` -- that module imports
    numpy and osgeo at module scope (see its header), which this script has
    no other reason to require. Uses the exact same regex audit_pure.py
    section 7 uses for the other declarations it checks, so the two can
    never disagree about what counts as "the version line".
    """
    lib_path = os.path.join(src_dir, "dem2dged_lib.py")
    if not os.path.isfile(lib_path):
        raise VersionInfoError(
            "%s not found -- run this script from the project root (the "
            "folder that contains dem2dged_lib.py)." % lib_path)
    text = open(lib_path, encoding="utf-8").read()

    m = re.search(r'^VERSION\s*=\s*["\']([^"\']+)["\']', text, re.M)
    if not m:
        raise VersionInfoError(
            "could not find a line matching VERSION = \"X.Y\" in %s -- "
            "dem2dged_lib.py's format may have changed; update the regex "
            "in make_version_info.py to match." % lib_path)
    version = m.group(1)

    m = re.search(r'^RELEASE_STAGE\s*=\s*["\']([^"\']*)["\']', text, re.M)
    release_stage = m.group(1) if m else ""

    version_display = ("%s-%s" % (version, release_stage)
                        if release_stage else version)
    return version, version_display


def version_to_tuple(version):
    """"0.45" -> (0, 45, 0, 0). Windows FILEVERSION/PRODUCTVERSION always
    need exactly four non-negative 16-bit integers; dem2dged's MAJOR.MINOR-
    only scheme (see dem2dged_lib.py's comment above VERSION) supplies the
    first two and this pads build/revision with 0. A stray "-beta"/"-rcN"
    suffix is stripped before parsing so this never raises on a display
    string, even though RELEASE_STAGE is carried separately today.
    """
    numeric = re.split(r"[-+]", version, 1)[0]
    parts = [p for p in numeric.split(".") if p != ""]
    if not parts:
        raise VersionInfoError(
            "VERSION %r has no numeric parts to build a Windows FILEVERSION "
            "from." % version)
    try:
        nums = [int(p) for p in parts]
    except ValueError:
        raise VersionInfoError(
            "VERSION %r has a non-numeric component -- cannot build a "
            "Windows FILEVERSION tuple from it." % version)
    nums = (nums + [0, 0, 0, 0])[:4]
    for n in nums:
        if not (0 <= n <= 65535):
            raise VersionInfoError(
                "VERSION %r produces an out-of-range component %d (Windows "
                "FILEVERSION fields are 16-bit: 0-65535)." % (version, n))
    return tuple(nums)


def build_version_info_text(product_key):
    """Return (version_file_text, version_display) for product_key ("gui"
    or "validate"). Raises VersionInfoError on any problem; never writes
    anything or exits the process -- that is main()'s job, so this function
    is safe for other scripts to import and call directly.
    """
    if product_key not in PRODUCTS:
        raise VersionInfoError(
            "unknown product %r -- expected one of: %s"
            % (product_key, ", ".join(sorted(PRODUCTS))))
    p = PRODUCTS[product_key]
    version, version_display = read_project_version()
    file_tuple = ", ".join(str(n) for n in version_to_tuple(version))
    text = VERSION_FILE_TEMPLATE.format(
        file_tuple=file_tuple,
        company_name=COMPANY_NAME,
        file_description=p["file_description"],
        version_display=version_display,
        internal_name=p["internal_name"],
        copyright=COPYRIGHT,
        original_filename=p["original_filename"],
        product_name=p["product_name"],
    )
    return text, version_display


def main(argv):
    if len(argv) < 2 or argv[1] not in PRODUCTS:
        print("Usage: python make_version_info.py {gui|validate} [output_path]")
        print()
        print("  gui       -- version info for dem2dged.exe (dem2dged.spec)")
        print("  validate  -- version info for dem2dged_validate.exe "
              "(dem2dged_validate.spec)")
        return 2
    product_key = argv[1]
    output_path = (argv[2] if len(argv) > 2 else
                   os.path.join(HERE, PRODUCTS[product_key]["default_output"]))

    try:
        text, version_display = build_version_info_text(product_key)
    except VersionInfoError as e:
        print("ERROR: %s" % e)
        return 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
    print("[OK] Wrote %s (dem2dged v%s)" % (output_path, version_display))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
