# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Eui Soo SON
# Version: 0.42
# (single source of truth: dem2dged_lib.VERSION -- audit_pure.py
#  section 7 checks every declaration in the project against it)

"""Release gate for dem2dged v0.42 -- run this locally, return the logs.

WHY THIS EXISTS
---------------
Everything in this script that does NOT need GDAL has already been run and
passes. What has NOT been verified anywhere is the half that needs a real
GDAL: the actual gdalwarp calls, the geoid transforms, the tile geometry on
disk, and the validator running against tiles it did not fabricate. That is
what this script exercises, and it writes a detailed log for every step so
the results can be reviewed without guessing.

HOW TO RUN IT  (Anaconda Prompt -- not PowerShell, not cmd, not base)
---------------------------------------------------------------------
    conda activate DGED
    cd /d C:\\Users\\Son\\Documents\\DEM2DGED\\dem2dged_v0.41
    python RELEASE_CHECK_v0.41.py

NOTE (v0.42): this used to say "cd ... dem2dged_v0.40" -- a stale example
path pointing at a different, sibling folder. Every log this script has
ever produced was generated by an operator following that exact
instruction, so every "PASS" it reported described dem2dged_v0.40, not
whichever folder was actually meant to ship (the direct cause of the v0.42
"tests/ is missing" finding -- see CODE_REVIEW_v0.42.md). This script
itself was never at fault: HERE = dirname(__file__) below always operates
on wherever it is actually run from, regardless of what this comment says.
Only the example command was wrong. Always confirm the "Project folder:"
line in 00_environment.txt matches the folder you meant to check.

If the DGED environment does not exist yet, create a DEDICATED one first --
never install GDAL into `base`, it is the most reliable way to produce
dependency conflicts that are then very hard to unpick:

    conda create -n DGED python=3.11 -c conda-forge
    conda activate DGED
    conda install -c conda-forge gdal numpy pytest

Everything lands in _release_check_logs\\ :

    00_environment.txt      python / GDAL / PROJ / package versions
    00b_gdal_flags.txt      measured gdal/ogr/osr exception-flag behaviour
    01_compile.txt          byte-compilation of every module
    02_audit_pure.txt       the GDAL-free self-audit
    03_pytest.txt           the full pytest suite
    04_cli_help.txt         every CLI entry point's --help / --version
    05_geo_convert.txt      a real GEO conversion end to end
    06_geo_validate.txt     the validator against those real tiles
    07_utm_convert.txt      a real UTM conversion end to end
    08_utm_validate.txt     the validator against those real tiles
    09_tile_inspection.txt  gdalinfo-level inspection of the tiles produced
    10_run_verification.txt the 19-step harness (only if DEM\\ has rasters)
    SUMMARY.txt             one PASS/FAIL line per step  <-- send this first

Send SUMMARY.txt, plus any log whose line reads FAIL.
"""

import datetime
import glob
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = os.path.join(HERE, "_release_check_logs")
SUMMARY = []


def stamp():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def log(name, text):
    os.makedirs(LOG_DIR, exist_ok=True)
    path = os.path.join(LOG_DIR, name)
    with open(path, "w", encoding="utf-8", errors="replace") as f:
        f.write(text if isinstance(text, str) else str(text))
    return path


def summ(status, step, detail=""):
    line = "%-6s %-28s %s" % (status, step, detail)
    SUMMARY.append(line)
    print(line)


def run(cmd, cwd=None, env=None):
    """Run a command, capture everything, never raise."""
    try:
        p = subprocess.run(cmd, cwd=cwd or HERE, env=env,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                           timeout=1800)
        out = p.stdout.decode("utf-8", errors="replace")
        return p.returncode, out
    except Exception as e:                                # pragma: no cover
        return 999, "COULD NOT RUN %r: %s" % (cmd, e)


# ---------------------------------------------------------------------------
# 00 environment
# ---------------------------------------------------------------------------
def step_environment():
    lines = ["dem2dged release check  -  %s" % stamp(),
             "Project folder: %s" % HERE,
             "Executable:     %s" % sys.executable,
             "Python:         %s" % sys.version.replace("\n", " "),
             "CONDA_PREFIX:   %s" % os.environ.get("CONDA_PREFIX", "(not set)"),
             "GDAL_DATA:      %s" % os.environ.get("GDAL_DATA", "(not set)"),
             "PROJ_LIB:       %s" % os.environ.get("PROJ_LIB", "(not set)"),
             ""]

    ok = True
    try:
        from osgeo import gdal, osr
        lines.append("osgeo.gdal version: %s" % gdal.__version__)
        lines.append("gdal data dir:      %s" % gdal.GetConfigOption("GDAL_DATA"))
        try:
            lines.append("PROJ version:       %d.%d.%d"
                         % (osr.GetPROJVersionMajor(), osr.GetPROJVersionMinor(),
                            osr.GetPROJVersionMicro()))
        except Exception as e:
            lines.append("PROJ version:       (unavailable: %s)" % e)
    except Exception as e:
        ok = False
        lines.append("FATAL: cannot import osgeo -- %s" % e)
        lines.append("You are almost certainly not in the DGED environment.")

    for mod in ("numpy", "pytest", "PyInstaller"):
        try:
            m = __import__(mod)
            lines.append("%-12s %s" % (mod, getattr(m, "__version__", "?")))
        except Exception as e:
            lines.append("%-12s MISSING (%s)" % (mod, e))

    lines.append("")
    for exe in ("gdalwarp", "gdalinfo", "gdal_translate"):
        lines.append("%-16s %s" % (exe, shutil.which(exe) or "NOT ON PATH"))

    lines.append("")
    lines.append("-- conda list (filtered) --")
    rc, out = run(["conda", "list"])
    if rc == 0:
        for l in out.splitlines():
            if any(k in l.lower() for k in ("gdal", "proj", "numpy", "python ",
                                            "libgdal", "pytest", "pyinstaller")):
                lines.append(l)
    else:
        lines.append("(conda list unavailable: rc=%s)" % rc)

    log("00_environment.txt", "\n".join(lines))
    summ("PASS" if ok else "FAIL", "00 environment",
         "GDAL importable" if ok else "osgeo NOT importable -- stop here")
    return ok


# ---------------------------------------------------------------------------
# 00b GDAL exception-flag behaviour (measured, not assumed)
# ---------------------------------------------------------------------------
def step_gdal_flags():
    """Record what this GDAL build actually does with the exception flags.

    v0.41 discovered by measurement that gdal/ogr/osr share ONE global flag
    on GDAL 3.13.2 -- "gdal on, osr off" silently collapsed to "all off".
    dem2dged_lib.py's error-handling contract depends on that, so it is
    worth recording per environment rather than trusting a comment.
    """
    code = (
        "import sys; sys.path.insert(0, r'%s')\n"
        "from osgeo import gdal, ogr, osr\n"
        "print('after import, before dem2dged_lib:')\n"
        "print('  gdal=%%s ogr=%%s osr=%%s' %% (gdal.GetUseExceptions(),"
        " ogr.GetUseExceptions(), osr.GetUseExceptions()))\n"
        "gdal.UseExceptions()\n"
        "print('after gdal.UseExceptions():')\n"
        "print('  gdal=%%s ogr=%%s osr=%%s' %% (gdal.GetUseExceptions(),"
        " ogr.GetUseExceptions(), osr.GetUseExceptions()))\n"
        "osr.DontUseExceptions()\n"
        "print('after osr.DontUseExceptions():')\n"
        "print('  gdal=%%s ogr=%%s osr=%%s' %% (gdal.GetUseExceptions(),"
        " ogr.GetUseExceptions(), osr.GetUseExceptions()))\n"
        "shared = gdal.GetUseExceptions() == 0\n"
        "print('SHARED_FLAG=%%s' %% shared)\n"
        "import dem2dged_lib as dl\n"
        "print('after importing dem2dged_lib (what the tool runs as):')\n"
        "print('  gdal=%%s ogr=%%s osr=%%s' %% (gdal.GetUseExceptions(),"
        " ogr.GetUseExceptions(), osr.GetUseExceptions()))\n"
        "print('gdal_open on a bad path ->', dl.gdal_open('does_not_exist.tif'))\n"
    ) % HERE
    rc, out = run([sys.executable, "-W", "error::FutureWarning", "-c", code])
    log("00b_gdal_flags.txt", out)
    ok = rc == 0 and "gdal_open on a bad path -> None" in out
    shared = "SHARED_FLAG=True" in out
    summ("PASS" if ok else "FAIL", "00b GDAL flag behaviour",
         "shared flag=%s, gdal_open contract holds=%s" % (shared, ok))
    return ok


# ---------------------------------------------------------------------------
# 01 byte-compile
# ---------------------------------------------------------------------------
def step_compile():
    import py_compile

    lines, bad = [], []
    targets = sorted(glob.glob(os.path.join(HERE, "*.py"))
                     + glob.glob(os.path.join(HERE, "tests", "*.py"))
                     + glob.glob(os.path.join(HERE, "dem2dged_validate_v*", "*.py")))
    for f in targets:
        rel = os.path.relpath(f, HERE)
        try:
            py_compile.compile(f, doraise=True)
            lines.append("OK   %s" % rel)
        except Exception as e:
            bad.append(rel)
            lines.append("FAIL %s\n     %s" % (rel, e))
    lines.insert(0, "%d module(s) checked, %d failed\n" % (len(targets), len(bad)))
    log("01_compile.txt", "\n".join(lines))
    summ("PASS" if not bad else "FAIL", "01 byte-compile",
         "%d modules" % len(targets) if not bad else "broken: %s" % bad)
    return not bad


# ---------------------------------------------------------------------------
# 02 audit_pure
# ---------------------------------------------------------------------------
def step_audit():
    rc, out = run([sys.executable, "audit_pure.py"])
    log("02_audit_pure.txt", out)
    ok = rc == 0 and "RESULT: 0 problem(s)" in out
    tail = [l for l in out.splitlines() if l.startswith("RESULT:")]
    summ("PASS" if ok else "FAIL", "02 audit_pure.py",
         tail[-1] if tail else "rc=%s" % rc)
    return ok


# ---------------------------------------------------------------------------
# 03 pytest
# ---------------------------------------------------------------------------
def step_pytest():
    rc, out = run([sys.executable, "-m", "pytest", "-v", "--tb=short"])
    log("03_pytest.txt", out)
    ok = rc == 0
    tail = [l for l in out.splitlines() if " passed" in l or " failed" in l
            or " error" in l]
    summ("PASS" if ok else "FAIL", "03 pytest",
         tail[-1].strip() if tail else "rc=%s" % rc)
    return ok


# ---------------------------------------------------------------------------
# 04 CLI surface
# ---------------------------------------------------------------------------
def step_cli():
    blocks, bad = [], []
    checks = [
        ([sys.executable, "dem2dged.py", "--version"], "dem2dged --version"),
        ([sys.executable, "dem2dged.py", "--help"], "dem2dged --help"),
        ([sys.executable, "dem2dged_geo.py", "--help"], "dem2dged_geo --help"),
        ([sys.executable, "dem2dged_utm.py", "--help"], "dem2dged_utm --help"),
        ([sys.executable, "dem2dged_validate.py", "--version"],
         "dem2dged_validate --version"),
        ([sys.executable, "dem2dged_validate.py", "--help"],
         "dem2dged_validate --help"),
    ]
    for cmd, label in checks:
        rc, out = run(cmd)
        blocks.append("=" * 74 + "\n%s   (rc=%s)\n" % (label, rc) + "=" * 74
                      + "\n" + out)
        if rc != 0:
            bad.append(label)
    log("04_cli_help.txt", "\n".join(blocks))
    summ("PASS" if not bad else "FAIL", "04 CLI surface",
         "%d entry points" % len(checks) if not bad else "failed: %s" % bad)
    return not bad


# ---------------------------------------------------------------------------
# synthetic source DEMs (so this needs no operator data)
# ---------------------------------------------------------------------------
def _make_source(path, epsg, gt, w=400, h=300):
    import math
    import struct

    from osgeo import gdal, osr

    drv = gdal.GetDriverByName("GTiff")
    ds = drv.Create(path, w, h, 1, gdal.GDT_Float32)
    ds.SetGeoTransform(gt)
    srs = osr.SpatialReference()
    srs.ImportFromEPSG(epsg)
    ds.SetProjection(srs.ExportToWkt())
    ds.SetMetadataItem("AREA_OR_POINT", "Point")
    band = ds.GetRasterBand(1)
    band.SetNoDataValue(-32767.0)
    for j in range(h):
        row = [100.0 + 0.60 * i + 0.35 * j + 12.0 * math.sin(i / 7.0)
               + 8.0 * math.cos(j / 5.0) for i in range(w)]
        band.WriteRaster(0, j, w, 1, struct.pack("<%df" % w, *row),
                         buf_type=gdal.GDT_Float32)
    band.FlushCache(); ds.FlushCache(); ds = None
    return path


# ---------------------------------------------------------------------------
# 05-08 real conversions + validation
# ---------------------------------------------------------------------------
def step_convert_and_validate(mode, scratch):
    """mode is 'geo' or 'utm'. Returns (ok, out_dir)."""
    src = os.path.join(scratch, "%s_source.tif" % mode)
    out = os.path.join(scratch, "%s_tiles" % mode)
    os.makedirs(out, exist_ok=True)

    if mode == "geo":
        _make_source(src, 4326, (12.0, 1 / 3600.0, 0.0, 55.5, 0.0, -1 / 3600.0))
        cmd = [sys.executable, "dem2dged.py", src, out,
               "--mode", "geo", "--level", "5", "--verbose"]
        n_convert, n_validate = "05_geo_convert.txt", "06_geo_validate.txt"
    else:
        # 1200 x 300 posts at 10 m = 12 km x 3 km. A level-5 UTM tile is
        # (5001-1) * 2 m = 10 km, so this deliberately spans TWO tiles in x
        # and exercises section G (shared-edge reconciliation) on the UTM
        # side too -- the first v0.41 run produced a single tile from a
        # 4 km source and section G could only warn "no adjacent pairs".
        _make_source(src, 32632, (500000.0, 10.0, 0.0, 6150000.0, 0.0, -10.0),
                     w=1200, h=300)
        cmd = [sys.executable, "dem2dged.py", src, out,
               "--mode", "utm", "--level", "5", "--zone", "32N", "--verbose"]
        n_convert, n_validate = "07_utm_convert.txt", "08_utm_validate.txt"

    rc, cout = run(cmd)
    tifs = sorted(glob.glob(os.path.join(out, "*.tif")))
    header = ["command: %s" % " ".join(cmd), "returncode: %s" % rc,
              "tiles produced: %d" % len(tifs), ""]
    log(n_convert, "\n".join(header) + cout)
    conv_ok = rc == 0 and len(tifs) > 0
    summ("PASS" if conv_ok else "FAIL", "%s conversion" % n_convert[:2],
         "%s: %d tile(s)" % (mode.upper(), len(tifs)))
    if not conv_ok:
        return False, out

    # The unified CLI auto-validates; ALSO run the standalone validator so
    # both paths are exercised and we get a full report on disk.
    rep_txt = os.path.join(out, "STANDALONE_report.txt")
    rep_html = os.path.join(out, "STANDALONE_report.html")
    vcmd = [sys.executable, "dem2dged_validate.py", out,
            "-src", src, "-report", rep_txt, "-html-report", rep_html,
            "--verbose"]
    vrc, vout = run(vcmd)
    extra = []
    extra.append("command: %s" % " ".join(vcmd))
    extra.append("returncode: %s   (0 = no FAIL, 1 = at least one FAIL)" % vrc)
    auto_txt = os.path.join(out, "DGED_Validation_Report.txt")
    auto_html = os.path.join(out, "DGED_Validation_Report.html")
    extra.append("auto-validation report written by dem2dged.py: txt=%s html=%s"
                 % (os.path.isfile(auto_txt), os.path.isfile(auto_html)))
    extra.append("standalone report written: txt=%s html=%s"
                 % (os.path.isfile(rep_txt), os.path.isfile(rep_html)))
    extra.append("")
    log(n_validate, "\n".join(extra) + vout)

    val_ok = (vrc == 0 and os.path.isfile(auto_txt) and os.path.isfile(auto_html)
              and os.path.isfile(rep_txt) and os.path.isfile(rep_html))
    result = [l for l in vout.splitlines() if l.startswith("RESULT:")]
    summ("PASS" if val_ok else "FAIL", "%s validation" % n_validate[:2],
         "%s: %s" % (mode.upper(), result[-1] if result else "rc=%s" % vrc))
    return val_ok, out


# ---------------------------------------------------------------------------
# 09 tile inspection
# ---------------------------------------------------------------------------
def step_inspect(dirs):
    from osgeo import gdal

    import dem2dged_lib as dl

    lines, bad = [], []
    for d in dirs:
        for t in sorted(glob.glob(os.path.join(d, "*.tif"))):
            base = os.path.basename(t)
            ds = gdal.Open(t)
            if ds is None:
                bad.append(base)
                lines.append("FAIL  %s -- gdal.Open returned None" % base)
                continue
            band = ds.GetRasterBand(1)
            gt = ds.GetGeoTransform()
            dtype = gdal.GetDataTypeName(band.DataType)
            comp = ds.GetMetadataItem("COMPRESSION", "IMAGE_STRUCTURE")
            pred = ds.GetMetadataItem("PREDICTOR", "IMAGE_STRUCTURE")
            aop = ds.GetMetadataItem("AREA_OR_POINT")
            nod = band.GetNoDataValue()
            try:
                vmin, vmax = band.ComputeRasterMinMax(True)
            except Exception:
                vmin = vmax = None
            wkt = ds.GetProjection() or ""
            lines.append(
                "%s\n"
                "   size      %d x %d\n"
                "   dtype     %s        expected for the level via "
                "dem2dged_lib.output_type_for_level()\n"
                "   nodata    %s        (spec: -32767)\n"
                "   AREA_OR_POINT %s    (spec: Point)\n"
                "   compress  %s  predictor=%s   (spec 13.1: LZW; v0.39: "
                "3 for Float32, 2 for Int16)\n"
                "   pixel     %.10g x %.10g\n"
                "   origin    %.10f , %.10f\n"
                "   range     %s .. %s\n"
                "   EGM2008 tag present: %s"
                % (base, ds.RasterXSize, ds.RasterYSize, dtype, nod, aop,
                   comp, pred, gt[1], abs(gt[5]), gt[0], gt[3], vmin, vmax,
                   ("3855" in wkt or "EGM2008" in wkt.upper())))
            if comp != "LZW":
                bad.append("%s: compression=%s" % (base, comp))
            if nod is None or abs(nod + 32767) > 0.5:
                bad.append("%s: nodata=%s" % (base, nod))
            if (aop or "").upper() != "POINT":
                bad.append("%s: AREA_OR_POINT=%s" % (base, aop))
            if dtype == "Float32" and pred not in (None, "3"):
                bad.append("%s: Float32 with PREDICTOR=%s (expected 3)"
                           % (base, pred))
            if dtype == "Int16" and pred not in (None, "2"):
                bad.append("%s: Int16 with PREDICTOR=%s (expected 2)"
                           % (base, pred))
            ds = None
    lines.insert(0, "dem2dged_lib.VERSION = %s\n" % dl.VERSION)
    if bad:
        lines.append("\n\nPROBLEMS\n" + "\n".join("  " + b for b in bad))
    log("09_tile_inspection.txt", "\n".join(lines))
    summ("PASS" if not bad else "FAIL", "09 tile inspection",
         "all tiles conform" if not bad else "%d problem(s)" % len(bad))
    return not bad


# ---------------------------------------------------------------------------
# 10 full harness (only if the operator has DEMs in DEM\)
# ---------------------------------------------------------------------------
def step_harness():
    dem_dir = os.path.join(HERE, "DEM")
    rasters = (glob.glob(os.path.join(dem_dir, "**", "*.tif"), recursive=True)
               + glob.glob(os.path.join(dem_dir, "**", "*.tiff"), recursive=True))
    if not rasters:
        log("10_run_verification.txt",
            "SKIPPED -- no rasters found under %s\n"
            "Drop one or more source DEMs there and re-run to exercise the\n"
            "full 19-step harness against real terrain.\n" % dem_dir)
        summ("SKIP", "10 run_verification", "no rasters under DEM\\")
        return True
    rc, out = run([sys.executable, "run_verification.py"])
    log("10_run_verification.txt", out)
    ok = rc == 0
    tail = [l for l in out.splitlines() if "/" in l and "pass" in l.lower()]
    summ("PASS" if ok else "FAIL", "10 run_verification",
         tail[-1].strip() if tail else "rc=%s" % rc)
    return ok


# ---------------------------------------------------------------------------
def main():
    if os.path.isdir(LOG_DIR):
        shutil.rmtree(LOG_DIR, ignore_errors=True)
    os.makedirs(LOG_DIR, exist_ok=True)
    sys.path.insert(0, HERE)

    print("=" * 74)
    print(" dem2dged v0.42 release check  -  %s" % stamp())
    print(" logs -> %s" % LOG_DIR)
    print("=" * 74)

    if not step_environment():
        _finish()
        return 2

    step_gdal_flags()
    step_compile()
    step_audit()
    step_pytest()
    step_cli()

    scratch = tempfile.mkdtemp(prefix="dem2dged_relcheck_")
    dirs = []
    try:
        for mode in ("geo", "utm"):
            ok, out = step_convert_and_validate(mode, scratch)
            if ok:
                dirs.append(out)
        if dirs:
            step_inspect(dirs)
        else:
            summ("SKIP", "09 tile inspection", "no successful conversion")
        step_harness()
    finally:
        # Copy the reports out before the scratch dir disappears.
        keep = os.path.join(LOG_DIR, "reports")
        os.makedirs(keep, exist_ok=True)
        for d in dirs:
            for f in glob.glob(os.path.join(d, "*report*")) + \
                     glob.glob(os.path.join(d, "*Report*")):
                try:
                    shutil.copy2(f, os.path.join(
                        keep, os.path.basename(d) + "__" + os.path.basename(f)))
                except Exception:
                    pass
        shutil.rmtree(scratch, ignore_errors=True)

    return _finish()


def _finish():
    n_fail = sum(1 for l in SUMMARY if l.startswith("FAIL"))
    header = ["dem2dged v0.42 release check  -  %s" % stamp(),
              "Python: %s" % sys.version.split()[0],
              "=" * 74, ""]
    footer = ["", "=" * 74,
              "%d step(s) FAILED" % n_fail if n_fail else "ALL STEPS PASSED",
              "=" * 74]
    log("SUMMARY.txt", "\n".join(header + SUMMARY + footer))
    print("\n".join(footer))
    print("\nSend %s (and any log whose line says FAIL)."
          % os.path.join(LOG_DIR, "SUMMARY.txt"))
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
